### ISSUE TITLE
Immediately crashes when trying to use Google drive 

### ISSUE THREAD

**Issue by gabrielambuehl** [PhilippC/keepass2android#1287]
Since updating to 1.0.8b-pre1 keepass2android immediately crashes when I try to access database on Google drive.

**Comment by Blackbat007** [comment]
Doing the same for me too.

**Comment by garpunkal** [comment]
me three

**Comment by gabrielambuehl** [comment]
FWIW, I cleared app data, didn't help either

**Comment by Blackbat007** [comment]
So I have a workaround that seems to work for me at least. Choosing a database on Google Drive via the system file picker option works, but clicking directly on the Google Drive icon crashes the app.

**Comment by albertooka** [comment]
The same happens to me

**Comment by pjgoncalves72** [comment]
Same here, app crashes.

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(Unknown Source:27)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/GoogleAuthUtil;
	at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential.getToken(GoogleAccountCredential.java:255)
	at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:279)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:858)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
	at keepass2android.javafilestorage.GoogleDriveFileStorage.finishInitialization(GoogleDriveFileStorage.java:726)
	at keepass2android.javafilestorage.GoogleDriveFileStorage.initializeAccount(GoogleDriveFileStorage.java:715)
	at keepass2android.javafilestorage.GoogleDriveFileStorage.access$200(GoogleDriveFileStorage.java:44)
	at keepass2android.javafilestorage.GoogleDriveFileStorage$1.doInBackground(GoogleDriveFileStorage.java:647)
	at keepass2android.javafilestorage.GoogleDriveFileStorage$1.doInBackground(GoogleDriveFileStorage.java:640)
	at android.os.AsyncTask$3.call(Unknown Source:20)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
Caused by: java.lang.ClassNotFoundException: com.google.android.gms.auth.GoogleAuthUtil
	... 17 more

**Comment by sscheib** [comment]
yep, same here.
google pixel 2 xl with android 10

**Comment by mcfisch** [comment]
Same here on a rooted OnePlus 6T with the May 2020 firmware update of Android 10. App immediately crashes on start, likely because it tries loading the recent database from GDrive. Downloading the database and opening it from the local filesystem works fine. From there on the app no longer crashes.
However, after opening the DB from inside TotalCommander it shows an error popup on each start, but then goes ahead and opens it anyway.

**Comment by PhilippC** [comment]
sorry guys. Just uploaded 1.08-pre2 to beta channel which should fix this. Please let me know if it does!

**Comment by jesus-christ9** [comment]
Did not fix it for me, crashes immediately upon starting. Pixel 4 xl, android 10.

**Comment by aFooBar** [comment]
Same problem here
Unsinstalled and reinstalled (few minutes ago): no change: Crash on open
Installed Git version: works fine
--
Samsung S10e, Android 10 Stock,base on GDrive

**Comment by Blackbat007** [comment]
Version 1.08-pre2 has sorted the Google Drive issue for me.

Many thanks.

**Comment by mcfisch** [comment]
It fixed it for me. I've opened the file from within K2A using the GDrive connector with no issues now, and after locking and closing the DB it got automatically loaded at the next app start, and was unlocked via fingerprint as before. All good now for me, thanks!

Note: the change log still shows the "pre1" as the app version.

**Comment by jesus-christ9** [comment]
Apologies, 1.08-pre2 has solved the issue for me. Thought I was running the latest however it was pre-1, updating from GPlay fixed it. Thank you.

**Comment by RealGJ** [comment]
1.08-pre2 has solved my issue. Thanks a bunch 😊

**Comment by johnjjr** [comment]
1.08 pre2  working with gdrive

**Comment by gabrielambuehl** [comment]
Works for me again with latest upgrade.

Thanks a lot!

**Comment by mhbr12742** [comment]
> Since updating to 1.0.8b-pre1 keepass2android immediately crashes when I try to access database on Google drive.

I'm using Onedrive and see the same issues
